apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-sec
  labels:
    app: {{ .Values.appName }}-sec
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}-sec
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}-sec
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: {{ .Values.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.rtmp_port }}
          lifecycle:
            postStart:
              exec:
                command: ['/usr/bin/curl', {{ .Release.Name }}-inp-lb.{{ .Release.Namespace }}/join]
            preStop:
              exec:
                command: ['/usr/bin/curl',{{ .Release.Name }}-inp-lb.{{ .Release.Namespace }}/leave]
          env:
            - name: primary_url
              value: rtmp://{{ .Release.Name }}-inp-lb.{{ .Release.Namespace }}
            - name: ffmpeg_dir
              value: {{ .Values.ffmpeg_path }} 
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-prim
  labels:
    app: {{ .Values.appName }}-prim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}-prim
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}-prim
    spec:
      hostname: primary
      containers:
        - name: {{ .Values.appName }}
          image: {{ .Values.image }}
          imagePullPolicy: Always
          ports:
            - name: rtmp
              containerPort: {{ .Values.rtmp_port }}
              protocol: TCP
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: relay_url
              value: {{ .Values.relay_url }}
            - name: primary
              value: "1"
            - name: primary_addr
              value: {{ .Release.Name }}-inp-lb.{{ .Release.Namespace }}
            - name: ffmpeg_dir
              value: {{ .Values.ffmpeg_path }} 
---

kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-inp-lb 
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.appName }}-prim
  ports:
    - name: rtmp
      port: {{ .Values.rtmp_port }}
      targetPort: {{ .Values.rtmp_port }}
    - name: http
      port: 80
      targetPort: 80

---

kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-out-lb 
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.appName }}-sec
  ports:
    - name: http
      port: {{ .Values.rtmp_port }}
      targetPort: {{ .Values.rtmp_port }}
