kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-inp-lb
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.appName }}-prim
  ports:
    - name: rtmp
      port: {{ .Values.rtmp_port }}
      targetPort: {{ .Values.rtmp_port }}
    - name: http
      port: 80
      targetPort: 80
